Задачи по 4му занятию
js-tasks-ru/vue-20241213_yuvgulin pull request #4
Opened 2024-12-26 23:04 UTC by YuGulin

[MeetupView]
    [UiClock]
    [Удаляемые Email-ы]
    [Компонент-счётчик]
    [Компоненты: погода в Средиземье]

2024-12-26 23:04 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-27 21:52 UTC, ShGKme requested changes

2024-12-27 21:52 UTC, ShGKme commented on 03-components/30-removable-emails/MarkedEmailsApp.js
> +            <EmailList :emails="markedEmails" @remove="removeEmailByIndex($event)"/>
`@remove="removeEmailByIndex($event)"` тоже что `@remove="removeEmailByIndex"`

2024-12-27 21:52 UTC, ShGKme commented on 03-components/50-weather-components/components/WeatherCard.js
> +            <weather-card-conditions
Является совсем не строгой рекомендацией, но в современном Vue принят `PascalCase` для имён компонентов в шаблоне.

2024-12-27 21:52 UTC, ShGKme commented on 03-components/10-MeetupView/MeetupView.js
> +    },
Этот компонент не может нормально функционировать без параметра `meetup`. Он упадёт с `cannot read properties of undefined`. Для упрощения поиска ошибок с ним, нужно явно описывать такие параметры, как обязательные.

2025-01-14 21:35 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2025-01-14 21:38 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2025-01-14 21:44 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2025-01-14 21:49 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2025-01-15 15:17 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2025-01-15 15:21 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2025-01-15 15:52 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2025-01-15 16:30 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2025-01-15 20:03 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2025-01-15 20:12 UTC, ShGKme submitted a review, later dismissed
Принято

2025-01-15 20:12 UTC, ShGKme commented on 03-components/10-MeetupView/MeetupView.js
> +                        <MeetupAgenda v-if="meetup?.agenda?.length" :agenda="meetup.agenda" />
`meetup` описан, как обязательный параметр, поэтому его не нужно проверять на `null` через `?.`

2025-01-15 20:12 UTC, ShGKme commented on 04-sfc/20-MeetupCover-style-v-bind/MeetupCover.vue
> +    background-image: v-bind('image ? "url(" + image + ")" : "var(--default-cover)"');
На мой взгляд, лучше такие вычисления перенести в `computed`, оставляя стили проще. В отличие от шаблона, обычно в стилях совсем нет вычислений и связи с JS, нет хорошей поддержки IDE. Удобнее иметь там только имя свойства, а само вычисление оставлять в компоненте. И не будет страшного сгенерированного при компиляции имени CSS переменной.

2025-01-15 20:12 UTC, ShGKme commented on 04-sfc/20-MeetupCover-style-v-bind/MeetupCover.vue
> +    background-image: v-bind('image ? "url(" + image + ")" : "var(--default-cover)"');
Первый фон затемнения с `linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4))` потерялся.

2025-01-15 20:14 UTC, merged

2025-01-15 20:15 UTC, ShGKme commented
Бот уже принял PR, но были решены не все задачи. Их можно будет закончить в следующем PR.